In [88]:
import pandas as pd 
gt2025=pd.read_csv('~/Documents/synapse_ntclassification/hemi2025/202508-hemibrain_gt_data.csv')

In [212]:
picked = gt2025[gt2025['neurotransmitter_verified'].str.contains(r'\boctopamine-negative\b', case=False, na=False)]
# picked = gt2025[gt2025['neurotransmitter_verified'].str.contains(r'\btyramine\b(?!-negative)', case=False, na=False)]

# picked.to_csv('acetylcholine_positives.csv', index=False)

bodyID = picked['bodyid'].tolist()

picked

,bodyid,pre,type,species,region,hemilineage,neurotransmitter_verified,neurotransmitter_verified_source,neurotransmitter_verified_evidence,neurotransmitter_verified_confidence
278,511686666,315,CL357,adult_drosophila_melanogaster,central_brain,SMPp&v1_ventral,"acetylcholine-negative, glutamate-negative, ga...","Nern et al., 2024",EASI-FISH,4
279,5813078595,1445,CL357,adult_drosophila_melanogaster,central_brain,SMPp&v1_ventral,"acetylcholine-negative, glutamate-negative, ga...","Nern et al., 2024",EASI-FISH,4
504,734581598,513,Delta7,adult_drosophila_melanogaster,central_brain,PBp1,"glutamate, serotonin, acetylcholine-negative, ...","Wolff et al., 2024",EASI-FISH,4
506,880530613,504,Delta7,adult_drosophila_melanogaster,central_brain,PBp1,"glutamate, serotonin, acetylcholine-negative, ...","Wolff et al., 2024",EASI-FISH,4
508,880875736,479,Delta7,adult_drosophila_melanogaster,central_brain,PBp1,"glutamate, serotonin, acetylcholine-negative, ...","Wolff et al., 2024",EASI-FISH,4
...,...,...,...,...,...,...,...,...,...,...
30965,5813047626,282,hDeltaK,adult_drosophila_melanogaster,central_brain,DM1_CX_v,"acetylcholine, gaba-negative, glutamate-negati...","Wolff et al., 2024",EASI-FISH,4
30966,5813047626,282,hDeltaK,adult_drosophila_melanogaster,central_brain,DM2_CX_p,"acetylcholine, gaba-negative, glutamate-negati...","Wolff et al., 2024",EASI-FISH,4
30967,5813047626,282,hDeltaK,adult_drosophila_melanogaster,central_brain,DM3_CX_p,"acetylcholine, gaba-negative, glutamate-negati...","Wolff et al., 2024",EASI-FISH,4
30968,5813047626,282,hDeltaK,adult_drosophila_melanogaster,central_brain,DM4_CX_d3,"acetylcholine, gaba-negative, glutamate-negati...","Wolff et al., 2024",EASI-FISH,4
30969,5813047626,282,hDeltaK,adult_drosophila_melanogaster,central_brain,DM4_CX_p,"acetylcholine, gaba-negative, glutamate-negati...","Wolff et al., 2024",EASI-FISH,4

In [213]:
from neuprint import Client
from neuprint import fetch_neurons, NeuronCriteria as NC, SynapseCriteria as SC

TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN5bDU4QGNhbS5hYy51ayIsImxldmVsIjoibm9hdXRoIiwiaW1hZ2UtdXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jSjlLWkpQYUlWWFBsbWFLMjJjVUU3dXRMNjZYbTlHVTA3bEd4QjFYS0N0TmN4NkRnPXM5Ni1jP3N6PTUwP3N6PTUwIiwiZXhwIjoxOTM1NTkwNDcyfQ.IvbAYI5IDzes9eESIYpmXKVtufrGYmSHw-fMD3uC-Tg" # <--- Paste your token here
           # (or define NEUPRINT_APPLICATION CREDENTIALS in your environment)

c = Client('neuprint.janelia.org', 'hemibrain:v1.2.1', TOKEN)

neuron_df, conn_df = fetch_neurons(bodyID)

In [216]:
gt2025_pre = (
    gt2025[['bodyid', 'neurotransmitter_verified']]
    .drop_duplicates(subset='bodyid')  # keep first occurrence
    .rename(columns={'bodyid': 'bodyId', 'neurotransmitter_verified': 'from_gt'})
)

df_merged = neuron_df.merge(gt2025_pre, on='bodyId', how='left')

df_view = df_merged[['bodyId', 'pre', 'from_gt']]

df_filtered = df_view[df_view['from_gt'].str.contains('octopamine-negative', na=False)]

# Sort by 'pre' descending
df_ranked = df_filtered.sort_values(by='pre', ascending=False)

# Random sample 25 rows with a fixed seed
df = df_filtered.sample(n=25, random_state=42)

# Reset index (optional)
df = df.reset_index(drop=True)

df

        bodyId   pre                                            from_gt
0    915605750   373  acetylcholine, gaba-negative, glutamate-negati...
1   1442176747   289  glutamate, acetylcholine-negative, gaba-negati...
2    788400963   246  acetylcholine, gaba-negative, glutamate-negati...
3   1132176882   101  acetylcholine, gaba-negative, glutamate-negati...
4   1071151811   137  acetylcholine, serotonin, gaba-negative, gluta...
5   1013779115    87  acetylcholine, gaba-negative, glutamate-negati...
6   1226287821   101  acetylcholine, gaba-negative, glutamate-negati...
7   1008378448  1791  serotonin, glutamate-negative, acetylcholine-n...
8    453765256   277  glutamate, gaba-negative, acetylcholine-negati...
9    918334668  1379  acetylcholine, glutamate-negative, gaba-negati...
10  1072503117    89  acetylcholine, gaba-negative, glutamate-negati...
11  5813038173   622  glutamate, acetylcholine-negative, gaba-negati...
12   694562388   203  acetylcholine, gaba-negative, glutamate-negati...
13  5813044422   290  acetylcholine, gaba-negative, glutamate-negati...
14  1200070420   468  glutamate, gaba-negative, acetylcholine-negati...
15   911565319   297  acetylcholine, gaba-negative, glutamate-negati...
16   788427061   260  acetylcholine, gaba-negative, glutamate-negati...
17   419060083   556  tyramine, acetylcholine-negative, gaba-negativ...
18  1254947903   294  glutamate, acetylcholine-negative, gaba-negati...
19  1289799863   120  acetylcholine, serotonin, gaba-negative, gluta...
20  1009043211   368  acetylcholine, gaba-negative, glutamate-negati...
21  1261044051   184  acetylcholine, serotonin, gaba-negative, gluta...
22  5813041497   299  acetylcholine, gaba-negative, glutamate-negati...
23   948372363   329  acetylcholine, gaba-negative, glutamate-negati...
24   910438484   124  acetylcholine, serotonin, gaba-negative, gluta...

In [132]:
# # Drop specific rows
df_dropped = df_view.drop([1, 2, 6, 7, 8, 9, 11, 25])

df_unique = df_dropped.drop_duplicates(subset='bodyId', keep='first')

df = df_unique

df

       bodyId  pre                                            from_gt
0   204613133  209                                      gaba-negative
3   235985275  233                                      gaba-negative
4   236331138  249                                      gaba-negative
5   263475451  405                                      gaba-negative
10  265120597  370  acetylcholine, glutamate, gaba-negative, dopam...
12  266200011  125                                      gaba-negative
13  266536576  323                                      gaba-negative
14  294450004  190                                      gaba-negative
15  294783423   55                                      gaba-negative
16  294786785   73                                      gaba-negative
17  294791509  373  acetylcholine, glutamate, gaba-negative, dopam...
18  294792311   43                                      gaba-negative
19  295116165   77                                      gaba-negative
20  295120620  104                                      gaba-negative
21  295461302   77                                      gaba-negative
22  295461534   95                                      gaba-negative
23  295802733  404                                      gaba-negative
24  295820085  292                                      gaba-negative
26  296160764  230                                      gaba-negative
27  296199021  206                                      gaba-negative
28  296199149  233                                      gaba-negative
29  296203325  217                                      gaba-negative

In [215]:
top20id = df['bodyId'].tolist()
print(top20id)

[915605750, 1442176747, 788400963, 1132176882, 1071151811, 1013779115, 1226287821, 1008378448, 453765256, 918334668, 1072503117, 5813038173, 694562388, 5813044422, 1200070420, 911565319, 788427061, 419060083, 1254947903, 1289799863, 1009043211, 1261044051, 5813041497, 948372363, 910438484]

In [217]:
# Assumes:
#   from neuprint import fetch_synapse_connections, NeuronCriteria, SynapseCriteria
# If you prefer NC/SC aliases, uncomment the two alias lines below.

from neuprint import fetch_synapse_connections, NeuronCriteria, SynapseCriteria
# NC = NeuronCriteria
# SC = SynapseCriteria

import pandas as pd

def fetch_synapses_sequential(top20id,
                              batch_size=5000,
                              rois=None,
                              confidence=0,
                              deduplicate=True):
    """
    Runs fetch_synapse_connections() one ID at a time with error handling.
    Prints progress messages, skips failures, and merges all successful results.

    Returns (neuprint_df, success_ids, failed_ids)
    """
    # Prepare criteria that stay constant except for bodyId
    synapse_criteria = SynapseCriteria(rois=rois,confidence=confidence)

    results = []
    success_ids = []
    failed_ids = []

    for i, body_id in enumerate(top20id, start=1):
        print(f"[{i}/{len(top20id)}] Running bodyId={body_id} ...")
        try:
            neuron_criteria = NeuronCriteria(bodyId=body_id)
            df = fetch_synapse_connections(neuron_criteria, None, synapse_criteria,
                                           batch_size=batch_size)
            # Some neuprint functions can return None on empty results; handle that
            if df is None:
                print(f"  -> No results for bodyId={body_id} (received None). Skipping.")
            elif isinstance(df, pd.DataFrame) and df.empty:
                print(f"  -> No results for bodyId={body_id} (empty DataFrame). Skipping.")
            else:
                print(f"  -> Retrieved {len(df)} rows for bodyId={body_id}.")
                results.append(df)
                success_ids.append(body_id)

        except Exception as e:
            # Log and continue
            print(f"  !! Error with bodyId={body_id}: {e}")
            failed_ids.append(body_id)
            continue

    # Merge all successful DataFrames
    if results:
        neuprint_df = pd.concat(results, ignore_index=True, sort=False)
        if deduplicate:
            before = len(neuprint_df)
            neuprint_df = neuprint_df.drop_duplicates().reset_index(drop=True)
            after = len(neuprint_df)
            if after != before:
                print(f"Deduplicated merged DataFrame: {before} -> {after} rows.")
    else:
        # Create an empty placeholder DataFrame if nothing succeeded
        neuprint_df = pd.DataFrame()
        print("No successful results to merge.")

    # Final summary
    print("\n=== Summary ===")
    print(f"Total IDs provided: {len(top20id)}")
    print(f"Successful runs:    {len(success_ids)}")
    print(f"Failed runs:        {len(failed_ids)}")
    if failed_ids:
        print(f"Failed bodyIds:     {failed_ids}")

    return neuprint_df, success_ids, failed_ids


# ---- Example usage ----
# top20id = [425276848, 123456789, ...]  # your list of body IDs
neuprint_df, ok_ids, bad_ids = fetch_synapses_sequential(top20id)

# `neuprint_df` is the merged result you're calling "neuprint" in your snippet.
# If you want the same variable name:
# neuprint = neuprint_df

[1/25] Running bodyId=915605750 ...

  0%|          | 0/1471 [00:00<?, ?it/s]

  -> Retrieved 1471 rows for bodyId=915605750.
[2/25] Running bodyId=1442176747 ...

  0%|          | 0/1267 [00:00<?, ?it/s]

  -> Retrieved 1267 rows for bodyId=1442176747.
[3/25] Running bodyId=788400963 ...

  0%|          | 0/727 [00:00<?, ?it/s]

  -> Retrieved 727 rows for bodyId=788400963.
[4/25] Running bodyId=1132176882 ...

  0%|          | 0/386 [00:00<?, ?it/s]

  -> Retrieved 386 rows for bodyId=1132176882.
[5/25] Running bodyId=1071151811 ...

  0%|          | 0/722 [00:00<?, ?it/s]

  -> Retrieved 722 rows for bodyId=1071151811.
[6/25] Running bodyId=1013779115 ...

  0%|          | 0/337 [00:00<?, ?it/s]

  -> Retrieved 337 rows for bodyId=1013779115.
[7/25] Running bodyId=1226287821 ...

  0%|          | 0/351 [00:00<?, ?it/s]

  -> Retrieved 351 rows for bodyId=1226287821.
[8/25] Running bodyId=1008378448 ...

  0%|          | 0/5975 [00:00<?, ?it/s]

  -> Retrieved 5975 rows for bodyId=1008378448.
[9/25] Running bodyId=453765256 ...

  0%|          | 0/1717 [00:00<?, ?it/s]

  -> Retrieved 1717 rows for bodyId=453765256.
[10/25] Running bodyId=918334668 ...

  0%|          | 0/4985 [00:00<?, ?it/s]

  -> Retrieved 4985 rows for bodyId=918334668.
[11/25] Running bodyId=1072503117 ...

  0%|          | 0/359 [00:00<?, ?it/s]

  -> Retrieved 359 rows for bodyId=1072503117.
[12/25] Running bodyId=5813038173 ...

  0%|          | 0/1830 [00:00<?, ?it/s]

  -> Retrieved 1830 rows for bodyId=5813038173.
[13/25] Running bodyId=694562388 ...

  0%|          | 0/584 [00:00<?, ?it/s]

  -> Retrieved 584 rows for bodyId=694562388.
[14/25] Running bodyId=5813044422 ...

  0%|          | 0/746 [00:00<?, ?it/s]

  -> Retrieved 746 rows for bodyId=5813044422.
[15/25] Running bodyId=1200070420 ...

  0%|          | 0/1792 [00:00<?, ?it/s]

  -> Retrieved 1792 rows for bodyId=1200070420.
[16/25] Running bodyId=911565319 ...

  0%|          | 0/991 [00:00<?, ?it/s]

  -> Retrieved 991 rows for bodyId=911565319.
[17/25] Running bodyId=788427061 ...

  0%|          | 0/942 [00:00<?, ?it/s]

  -> Retrieved 942 rows for bodyId=788427061.
[18/25] Running bodyId=419060083 ...

  0%|          | 0/1317 [00:00<?, ?it/s]

  -> Retrieved 1317 rows for bodyId=419060083.
[19/25] Running bodyId=1254947903 ...

  0%|          | 0/1184 [00:00<?, ?it/s]

  -> Retrieved 1184 rows for bodyId=1254947903.
[20/25] Running bodyId=1289799863 ...

  0%|          | 0/512 [00:00<?, ?it/s]

  -> Retrieved 512 rows for bodyId=1289799863.
[21/25] Running bodyId=1009043211 ...

  0%|          | 0/968 [00:00<?, ?it/s]

  -> Retrieved 968 rows for bodyId=1009043211.
[22/25] Running bodyId=1261044051 ...

  0%|          | 0/1038 [00:00<?, ?it/s]

  -> Retrieved 1038 rows for bodyId=1261044051.
[23/25] Running bodyId=5813041497 ...

  0%|          | 0/978 [00:00<?, ?it/s]

  -> Retrieved 978 rows for bodyId=5813041497.
[24/25] Running bodyId=948372363 ...

  0%|          | 0/2041 [00:00<?, ?it/s]

  -> Retrieved 2041 rows for bodyId=948372363.
[25/25] Running bodyId=910438484 ...

  0%|          | 0/579 [00:00<?, ?it/s]

  -> Retrieved 579 rows for bodyId=910438484.

=== Summary ===
Total IDs provided: 25
Successful runs:    25
Failed runs:        0

In [220]:
import pandas as pd
import random

df = neuprint_df

def filter_and_sample_ranked(df, neurotransmitter, num_neurons=20, samples_per_neuron=50, seed=42):
    random.seed(seed)
    
    df = df[df['confidence_pre'] >= 0.99]
    synapse_counts = df.groupby('bodyId_pre').size().reset_index(name='synapse_count')
    synapse_counts = synapse_counts.sort_values(by='synapse_count', ascending=False)
    
    print(f"Total unique neurons for {neurotransmitter}: {len(synapse_counts)}")
    
    # Rank and display top neurons
    top_neurons = synapse_counts.head(num_neurons)
    print("Top neurons by synapse count:")
    print(top_neurons)
    
    final_rows = []
    neuron_counter = 1
    
    for _, row in top_neurons.iterrows():
        neuron_id = row['bodyId_pre']
        neuron_df = df[df['bodyId_pre'] == neuron_id]
        
        if len(neuron_df) >= samples_per_neuron:
            sampled_rows = neuron_df.sample(n=samples_per_neuron, random_state=seed)
            sampled_rows['neuron_class'] = f'neuron{neuron_counter}'
            final_rows.append(sampled_rows)
            neuron_counter += 1
        else:
            print(f"Neuron {neuron_id} skipped (only {len(neuron_df)} synapses available).")
    
    if not final_rows:
        print(f"No neurons were sampled successfully for {neurotransmitter}.")
        return None

    final_df = pd.concat(final_rows)
    expected_rows = (neuron_counter - 1) * samples_per_neuron
    if len(final_df) != expected_rows:
        print(f"Warning: Final dataframe has {len(final_df)} rows, expected {expected_rows}.")

    final_df['neurotransmitter'] = neurotransmitter
    cols = ['neurotransmitter', 'neuron_class'] + [col for col in final_df.columns if col not in ['neurotransmitter', 'neuron_class']]
    final_df = final_df[cols]
    return final_df


neurotransmitter = 'octopamine-negative'
final_df = filter_and_sample_ranked(df, neurotransmitter)

final_df.to_csv(f'{neurotransmitter}_points.csv',index=False)

Total unique neurons for octopamine-negative: 25
Top neurons by synapse count:
    bodyId_pre  synapse_count
6    911565319            560
4    788427061            444
8    918334668            326
16  1200070420            321
1    453765256            290
3    788400963            212
2    694562388            192
22  5813038173            185
10  1008378448            139
20  1289799863             95
13  1071151811             92
12  1013779115             90
19  1261044051             90
23  5813041497             83
11  1009043211             82
7    915605750             81
24  5813044422             66
18  1254947903             62
5    910438484             60
17  1226287821             59

In [221]:
centroid = pd.read_csv(f'{neurotransmitter}_points.csv')

def calculate_bbox_around_pre(row, bbox_expansion):
    # Use pre-synaptic coordinates as center
    centroid_x = row['x_pre']
    centroid_y = row['y_pre']
    centroid_z = row['z_pre']

    # Define the bounding box
    bbox_xmin = centroid_x - bbox_expansion
    bbox_xmax = centroid_x + bbox_expansion
    bbox_ymin = centroid_y - bbox_expansion
    bbox_ymax = centroid_y + bbox_expansion
    bbox_zmin = centroid_z - bbox_expansion
    bbox_zmax = centroid_z + bbox_expansion

    # Check if post-synaptic point is within the bounding box
    x_out_of_range = not (bbox_xmin <= row['x_post'] <= bbox_xmax)
    y_out_of_range = not (bbox_ymin <= row['y_post'] <= bbox_ymax)
    z_out_of_range = not (bbox_zmin <= row['z_post'] <= bbox_zmax)

    any_out_of_range = x_out_of_range or y_out_of_range or z_out_of_range

    return pd.Series({
        'centroid_x': centroid_x,
        'centroid_y': centroid_y,
        'centroid_z': centroid_z,
        'bbox_xmin': bbox_xmin,
        'bbox_xmax': bbox_xmax,
        'bbox_ymin': bbox_ymin,
        'bbox_ymax': bbox_ymax,
        'bbox_zmin': bbox_zmin,
        'bbox_zmax': bbox_zmax,
        'any_out_of_range': any_out_of_range
    })


# Set the customizable bounding box expansion value
bbox_expansion_value = 65 

# Apply the function to each row, passing the custom bbox expansion value
centroid[['centroid_x', 'centroid_y', 'centroid_z', 
          'bbox_xmin', 'bbox_xmax', 'bbox_ymin', 'bbox_ymax', 'bbox_zmin', 'bbox_zmax', 
          'any_out_of_range']] = centroid.apply(calculate_bbox_around_pre, axis=1, bbox_expansion=bbox_expansion_value)

# Specify the columns you want to save
# columns_to_save = [
#     'neuron_class','gt_neurotransmitter', 'max_nt_value','conf', 'body', 'bodyId_pre', 'bodyId_post',
#     'bbox_xmin', 'bbox_xmax', 'bbox_ymin', 'bbox_ymax', 'bbox_zmin', 'bbox_zmax',
#     'x_pre', 'y_pre', 'z_pre', 'x_post', 'y_post', 'z_post', 
#     'any_out_of_range'  # Single column to indicate out of range
# ]

columns_to_save = [
    'neurotransmitter','neuron_class','bodyId_pre', 'bodyId_post',
    'bbox_xmin', 'bbox_xmax', 'bbox_ymin', 'bbox_ymax', 'bbox_zmin', 'bbox_zmax',
    'x_pre', 'y_pre', 'z_pre', 'x_post', 'y_post', 'z_post', 
    'any_out_of_range' 
]

# Filter rows where any coordinate is out of range
out_of_range_data = centroid[centroid['any_out_of_range']]

if not out_of_range_data.empty:
    count = len(out_of_range_data)
    out_of_range_data[columns_to_save].to_csv('out_of_range_neurons.csv', index=False)
    print(f"{count} out-of-range entries saved to 'out_of_range_neurons.csv'.")
else:
    print("No out-of-range data found.")

# Save the full DataFrame back to CSV with the selected columns
centroid[columns_to_save].to_csv(f'{neurotransmitter}_bbox.csv', index=False)
print("Full data with centroids and bounding boxes saved to 'bbox.csv'.")

No out-of-range data found.
Full data with centroids and bounding boxes saved to 'bbox.csv'.